services:
  - type: web
    name: mini-twitter-backend
    env: node
    rootDir: backend
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 5000 